"""add new column created_at to promo

Revision ID: 922783be78e5
Revises: a48bd5f71650
Create Date: 2025-01-23 18:25:43.004774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922783be78e5'
down_revision: Union[str, None] = 'a48bd5f71650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promos', 'created_at')
    # ### end Alembic commands ###
