"""[enhance] add default value to activated_at column in user_promo_activations table

Revision ID: 94616360e63f
Revises: 264173c6d26b
Create Date: 2025-01-26 15:33:58.946531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94616360e63f'
down_revision: Union[str, None] = '264173c6d26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
