"""Initial migration

Revision ID: d9626b6f5dc3
Revises: 
Create Date: 2025-01-22 19:34:35.081278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9626b6f5dc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=350), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('promos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('image_url', sa.String(length=350), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.Enum('COMMON', 'UNIQUE', name='promomodeenum'), nullable=False),
    sa.Column('promo_common', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['business_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('promo_unique_values',
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.Column('unique_code', sa.String(length=30), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.PrimaryKeyConstraint('promo_id', 'unique_code')
    )
    op.create_table('user_promo_activations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_promo_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'promo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promo_likes')
    op.drop_table('user_promo_activations')
    op.drop_table('promo_unique_values')
    op.drop_table('comments')
    op.drop_table('promos')
    op.drop_table('users')
    op.drop_table('business_companies')
    # ### end Alembic commands ###
